# -*- coding: utf-8 -*-
"""Installations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zmotp3yMH6uJ2l2oTgBsIl85NvadYg-O
"""

!pip install cmake
!pip install dlib
!pip install face-recognition
!pip install cvzone

!pip install opencv-python

